version: "3"
services:
    frontend:
        image: node:16-slim
        volumes:
            - ./frontend:/app/
        depends_on:
            - api-bars
            - api-users
        command: bash -c "cd /frontend && npm i && npm start:docker"
    api-bars:
        build:
            context: ./api-bars
            dockerfile: Dockerfile
        volumes:
            - ./api-bars:/app/
    api-users:
        build:
            context: ./api-users
            dockerfile: Dockerfile
        volumes:
            - ./api-users:/app/
    postgres:
        image: postgres:13.3-alpine
        shm_size: 2g
        environment:
          POSTGRES_DB: db_roadtrip
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_HOSTNAME: postgres
          POSTGRES_PORT: 5432
        volumes:
          - ./data-pgsql:/var/lib/postgresql/data
    proxy:
        image: nginx:1.23
        ports:
          - 80:80
        depends_on:
          - api-bars
          - api-users
          - frontend
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro