name: Tests
on:
    push:
        branches:
            -'**'
jobs:
    ci-frontend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./api-bar
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
                  cache-dependency-path: api-bar/package-lock.json
            - name: Install modules
              run: npm ci
            - name: Eslint check
              run: npx eslint .eslintrc.js
            - name: Testing
              run: |
                  npm run test
                  npm run test:e2e