name: Pipeline-CI Frontend
on:
    push:
        branches:
            - '**'
jobs:
    ci-frontend:
        runs-on: ubuntu-latest
        continue-on-error: false
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - name: Install modules
              run: npm ci
            - name: Eslint check
              run: npx eslint .eslintrc.js